name: Docker Build and Push

on:
  push:
    branches:
      - main  # change if your default branch is 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend (Dev)
        run: |
          IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/bmi-backend-dev:${{ github.sha }}
          docker build -t $IMAGE_TAG -f backend/Dockerfile.dev backend
          docker push $IMAGE_TAG

      - name: Build and Push Frontend (Dev)
        run: |
          IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/bmi-frontend-dev:${{ github.sha }}
          docker build -t $IMAGE_TAG -f frontend/Dockerfile.dev frontend
          docker push $IMAGE_TAG
